name: Auto Label Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Add GSSoC label to every issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            gssoc'26

      - name: Check if first-time contributor
        id: first_issue
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.issue.user.login;

            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                creator: creator,
                state: 'all'
              }
            );

            // Only current issue exists
            const isFirstIssue = issues.length === 1;

            core.setOutput("first_issue", isFirstIssue);

      - name: Add good first issue label
        if: steps.first_issue.outputs.first_issue == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            good first issue
